CLASS zcl_lab_12_linux_4919 DEFINITION INHERITING FROM zcl_lab_11_system_4919
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_12_LINUX_4919 IMPLEMENTATION.
ENDCLASS.
