CLASS zcl_lab_23_company_4919 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner_4919.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA capital TYPE string VALUE 'Quito'.
ENDCLASS.



CLASS ZCL_LAB_23_COMPANY_4919 IMPLEMENTATION.
ENDCLASS.
